# 矩阵

In [1]:
A = [1 2 3;
    4 5 6;
    7 8 9;]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [2]:
size(A)

(3, 3)

In [3]:
using LinearAlgebra

In [4]:
I

UniformScaling{Bool}
true*I

In [5]:
B = rand(1:16, 4, 4)

4×4 Array{Int64,2}:
 12  15   8   4
 11  11  13  14
  6   2   1   5
  6  16   5  16

In [6]:
[B I]

4×8 Array{Int64,2}:
 12  15   8   4  1  0  0  0
 11  11  13  14  0  1  0  0
  6   2   1   5  0  0  1  0
  6  16   5  16  0  0  0  1

In [7]:
[B; I]

8×4 Array{Int64,2}:
 12  15   8   4
 11  11  13  14
  6   2   1   5
  6  16   5  16
  1   0   0   0
  0   1   0   0
  0   0   1   0
  0   0   0   1

In [10]:
eye(n) = 1.0 * Matrix(I, n, n)

eye (generic function with 1 method)

In [12]:
E_3 = eye(3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [13]:
E_3' # 转置

3×3 Adjoint{Float64,Array{Float64,2}}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [15]:
E_3 * 3

3×3 Array{Float64,2}:
 3.0  0.0  0.0
 0.0  3.0  0.0
 0.0  0.0  3.0

In [16]:
E_3 + E_3

3×3 Array{Float64,2}:
 2.0  0.0  0.0
 0.0  2.0  0.0
 0.0  0.0  2.0

In [17]:
E_3 - E_3

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [18]:
# 对角阵

In [20]:
diagonal(x) = diagm(0 => x)

diagonal (generic function with 1 method)

In [21]:
diagonal([1, 2, 3])

3×3 Array{Int64,2}:
 1  0  0
 0  2  0
 0  0  3

In [22]:
function running_sum(n) # 生成一个对角线及以下都是1的矩阵
    S = zeros(n, n)
    for i = 1:n
        for j = 1:i
            S[i, j] = 1
        end
    end
    S
end


running_sum (generic function with 1 method)

In [23]:
running_sum(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0

In [26]:
# 范德蒙矩阵

In [31]:
function vandermonde(t, n)
    m = length(t)
    V = zeros(m, n)
    for i = 1:m
        for j = 1:n
            V[i, j] = t[i]^(j-1)
        end
    end
    V
end

vandermonde (generic function with 1 method)

In [32]:
vandermonde([-1, 0, -0.5, 1], 5)

4×5 Array{Float64,2}:
 1.0  -1.0  1.0   -1.0    1.0   
 1.0   0.0  0.0    0.0    0.0   
 1.0  -0.5  0.25  -0.125  0.0625
 1.0   1.0  1.0    1.0    1.0   

# 卷积
$p(x) = (1 + x)(2 - x + x^2) (1 + x - 2x^2) = 2 + 3x -3x^2 - x^3+x^4-2x^5$

In [35]:
using DSP

┌ Info: Precompiling DSP [717857b8-e6f2-59f4-9121-6e50c889abd2]
└ @ Base loading.jl:1186


In [36]:
a = [1, 1]; b = [2, -1, 1]; c = [1, 1, -2];

In [37]:
d = conv(conv(a, b), c)

6-element Array{Int64,1}:
  2
  3
 -3
 -1
  1
 -2

In [38]:
# 模拟卷积conv

In [39]:
function toeplize(b, n)
    m = length(b)
    T = zeros(n + m - 1, n)
    for i = 1:m
        T[i: n+m: end] .= b[i]
    end
    T
end

toeplize (generic function with 1 method)

In [40]:
b = [-1, 2, 3]; a = [-2, 3, -1, 1];
Tb = toeplize(b, length(a))

6×4 Array{Float64,2}:
 -1.0   0.0   0.0   0.0
  2.0  -1.0   0.0   0.0
  3.0   2.0  -1.0   0.0
  0.0   3.0   2.0  -1.0
  0.0   0.0   3.0   2.0
  0.0   0.0   0.0   3.0

In [41]:
Tb * a, conv(b, a)

([2.0, -7.0, 1.0, 6.0, -1.0, 3.0], [2, -7, 1, 6, -1, 3])